// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AddComponentOp.proto

#include "AddComponentOp.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace WorldsAdriftRebornCoreSdk {
PROTOBUF_CONSTEXPR AddComponentOp::AddComponentOp(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.components_)*/{}
  , /*decltype(_impl_.entityid_)*/int64_t{0}} {}
struct AddComponentOpDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddComponentOpDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddComponentOpDefaultTypeInternal() {}
  union {
    AddComponentOp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddComponentOpDefaultTypeInternal _AddComponentOp_default_instance_;
PROTOBUF_CONSTEXPR ComponentData::ComponentData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.componentid_)*/0u
  , /*decltype(_impl_.datalength_)*/0} {}
struct ComponentDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ComponentDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ComponentDataDefaultTypeInternal() {}
  union {
    ComponentData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ComponentDataDefaultTypeInternal _ComponentData_default_instance_;
}  // namespace WorldsAdriftRebornCoreSdk
static ::_pb::Metadata file_level_metadata_AddComponentOp_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_AddComponentOp_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_AddComponentOp_2eproto = nullptr;

const uint32_t TableStruct_AddComponentOp_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::WorldsAdriftRebornCoreSdk::AddComponentOp, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::WorldsAdriftRebornCoreSdk::AddComponentOp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::WorldsAdriftRebornCoreSdk::AddComponentOp, _impl_.entityid_),
  PROTOBUF_FIELD_OFFSET(::WorldsAdriftRebornCoreSdk::AddComponentOp, _impl_.components_),
  0,
  ~0u,
  PROTOBUF_FIELD_OFFSET(::WorldsAdriftRebornCoreSdk::ComponentData, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::WorldsAdriftRebornCoreSdk::ComponentData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::WorldsAdriftRebornCoreSdk::ComponentData, _impl_.componentid_),
  PROTOBUF_FIELD_OFFSET(::WorldsAdriftRebornCoreSdk::ComponentData, _impl_.data_),
  PROTOBUF_FIELD_OFFSET(::WorldsAdriftRebornCoreSdk::ComponentData, _impl_.datalength_),
  1,
  0,
  2,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::WorldsAdriftRebornCoreSdk::AddComponentOp)},
  { 10, 19, -1, sizeof(::WorldsAdriftRebornCoreSdk::ComponentData)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::WorldsAdriftRebornCoreSdk::_AddComponentOp_default_instance_._instance,
  &::WorldsAdriftRebornCoreSdk::_ComponentData_default_instance_._instance,
};

const char descriptor_table_protodef_AddComponentOp_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024AddComponentOp.proto\022\031WorldsAdriftRebo"
  "rnCoreSdk\"r\n\016AddComponentOp\022\025\n\010EntityId\030"
  "\001 \001(\003H\000\210\001\001\022<\n\nComponents\030\002 \003(\0132(.WorldsA"
  "driftRebornCoreSdk.ComponentDataB\013\n\t_Ent"
  "ityId\"}\n\rComponentData\022\030\n\013ComponentId\030\001 "
  "\001(\rH\000\210\001\001\022\021\n\004Data\030\002 \001(\014H\001\210\001\001\022\027\n\nDataLengt"
  "h\030\003 \001(\005H\002\210\001\001B\016\n\014_ComponentIdB\007\n\005_DataB\r\n"
  "\013_DataLengthb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_AddComponentOp_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_AddComponentOp_2eproto = {
    false, false, 300, descriptor_table_protodef_AddComponentOp_2eproto,
    "AddComponentOp.proto",
    &descriptor_table_AddComponentOp_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_AddComponentOp_2eproto::offsets,
    file_level_metadata_AddComponentOp_2eproto, file_level_enum_descriptors_AddComponentOp_2eproto,
    file_level_service_descriptors_AddComponentOp_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_AddComponentOp_2eproto_getter() {
  return &descriptor_table_AddComponentOp_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_AddComponentOp_2eproto(&descriptor_table_AddComponentOp_2eproto);
namespace WorldsAdriftRebornCoreSdk {

// ===================================================================

class AddComponentOp::_Internal {
 public:
  using HasBits = decltype(std::declval<AddComponentOp>()._impl_._has_bits_);
  static void set_has_entityid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

AddComponentOp::AddComponentOp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:WorldsAdriftRebornCoreSdk.AddComponentOp)
}
AddComponentOp::AddComponentOp(const AddComponentOp& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AddComponentOp* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.components_){from._impl_.components_}
    , decltype(_impl_.entityid_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.entityid_ = from._impl_.entityid_;
  // @@protoc_insertion_point(copy_constructor:WorldsAdriftRebornCoreSdk.AddComponentOp)
}

inline void AddComponentOp::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.components_){arena}
    , decltype(_impl_.entityid_){int64_t{0}}
  };
}

AddComponentOp::~AddComponentOp() {
  // @@protoc_insertion_point(destructor:WorldsAdriftRebornCoreSdk.AddComponentOp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AddComponentOp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.components_.~RepeatedPtrField();
}

void AddComponentOp::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AddComponentOp::Clear() {
// @@protoc_insertion_point(message_clear_start:WorldsAdriftRebornCoreSdk.AddComponentOp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.components_.Clear();
  _impl_.entityid_ = int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AddComponentOp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int64 EntityId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_entityid(&has_bits);
          _impl_.entityid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .WorldsAdriftRebornCoreSdk.ComponentData Components = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_components(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AddComponentOp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:WorldsAdriftRebornCoreSdk.AddComponentOp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional int64 EntityId = 1;
  if (_internal_has_entityid()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_entityid(), target);
  }

  // repeated .WorldsAdriftRebornCoreSdk.ComponentData Components = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_components_size()); i < n; i++) {
    const auto& repfield = this->_internal_components(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:WorldsAdriftRebornCoreSdk.AddComponentOp)
  return target;
}

size_t AddComponentOp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:WorldsAdriftRebornCoreSdk.AddComponentOp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .WorldsAdriftRebornCoreSdk.ComponentData Components = 2;
  total_size += 1UL * this->_internal_components_size();
  for (const auto& msg : this->_impl_.components_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // optional int64 EntityId = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_entityid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AddComponentOp::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AddComponentOp::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AddComponentOp::GetClassData() const { return &_class_data_; }


void AddComponentOp::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AddComponentOp*>(&to_msg);
  auto& from = static_cast<const AddComponentOp&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:WorldsAdriftRebornCoreSdk.AddComponentOp)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.components_.MergeFrom(from._impl_.components_);
  if (from._internal_has_entityid()) {
    _this->_internal_set_entityid(from._internal_entityid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AddComponentOp::CopyFrom(const AddComponentOp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:WorldsAdriftRebornCoreSdk.AddComponentOp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AddComponentOp::IsInitialized() const {
  return true;
}

void AddComponentOp::InternalSwap(AddComponentOp* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.components_.InternalSwap(&other->_impl_.components_);
  swap(_impl_.entityid_, other->_impl_.entityid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AddComponentOp::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_AddComponentOp_2eproto_getter, &descriptor_table_AddComponentOp_2eproto_once,
      file_level_metadata_AddComponentOp_2eproto[0]);
}

// ===================================================================

class ComponentData::_Internal {
 public:
  using HasBits = decltype(std::declval<ComponentData>()._impl_._has_bits_);
  static void set_has_componentid(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_data(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_datalength(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
};

ComponentData::ComponentData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:WorldsAdriftRebornCoreSdk.ComponentData)
}
ComponentData::ComponentData(const ComponentData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ComponentData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.data_){}
    , decltype(_impl_.componentid_){}
    , decltype(_impl_.datalength_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_data()) {
    _this->_impl_.data_.Set(from._internal_data(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.componentid_, &from._impl_.componentid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.datalength_) -
    reinterpret_cast<char*>(&_impl_.componentid_)) + sizeof(_impl_.datalength_));
  // @@protoc_insertion_point(copy_constructor:WorldsAdriftRebornCoreSdk.ComponentData)
}

inline void ComponentData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.data_){}
    , decltype(_impl_.componentid_){0u}
    , decltype(_impl_.datalength_){0}
  };
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ComponentData::~ComponentData() {
  // @@protoc_insertion_point(destructor:WorldsAdriftRebornCoreSdk.ComponentData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ComponentData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.Destroy();
}

void ComponentData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ComponentData::Clear() {
// @@protoc_insertion_point(message_clear_start:WorldsAdriftRebornCoreSdk.ComponentData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.data_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x00000006u) {
    ::memset(&_impl_.componentid_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.datalength_) -
        reinterpret_cast<char*>(&_impl_.componentid_)) + sizeof(_impl_.datalength_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ComponentData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 ComponentId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_componentid(&has_bits);
          _impl_.componentid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes Data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int32 DataLength = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_datalength(&has_bits);
          _impl_.datalength_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ComponentData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:WorldsAdriftRebornCoreSdk.ComponentData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // optional uint32 ComponentId = 1;
  if (_internal_has_componentid()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_componentid(), target);
  }

  // optional bytes Data = 2;
  if (_internal_has_data()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_data(), target);
  }

  // optional int32 DataLength = 3;
  if (_internal_has_datalength()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_datalength(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:WorldsAdriftRebornCoreSdk.ComponentData)
  return target;
}

size_t ComponentData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:WorldsAdriftRebornCoreSdk.ComponentData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional bytes Data = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_data());
    }

    // optional uint32 ComponentId = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_componentid());
    }

    // optional int32 DataLength = 3;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_datalength());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ComponentData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ComponentData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ComponentData::GetClassData() const { return &_class_data_; }


void ComponentData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ComponentData*>(&to_msg);
  auto& from = static_cast<const ComponentData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:WorldsAdriftRebornCoreSdk.ComponentData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_data(from._internal_data());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.componentid_ = from._impl_.componentid_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.datalength_ = from._impl_.datalength_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ComponentData::CopyFrom(const ComponentData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:WorldsAdriftRebornCoreSdk.ComponentData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ComponentData::IsInitialized() const {
  return true;
}

void ComponentData::InternalSwap(ComponentData* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.data_, lhs_arena,
      &other->_impl_.data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ComponentData, _impl_.datalength_)
      + sizeof(ComponentData::_impl_.datalength_)
      - PROTOBUF_FIELD_OFFSET(ComponentData, _impl_.componentid_)>(
          reinterpret_cast<char*>(&_impl_.componentid_),
          reinterpret_cast<char*>(&other->_impl_.componentid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ComponentData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_AddComponentOp_2eproto_getter, &descriptor_table_AddComponentOp_2eproto_once,
      file_level_metadata_AddComponentOp_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace WorldsAdriftRebornCoreSdk
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::WorldsAdriftRebornCoreSdk::AddComponentOp*
Arena::CreateMaybeMessage< ::WorldsAdriftRebornCoreSdk::AddComponentOp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::WorldsAdriftRebornCoreSdk::AddComponentOp >(arena);
}
template<> PROTOBUF_NOINLINE ::WorldsAdriftRebornCoreSdk::ComponentData*
Arena::CreateMaybeMessage< ::WorldsAdriftRebornCoreSdk::ComponentData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::WorldsAdriftRebornCoreSdk::ComponentData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
